### ISSUE TITLE
no token to mi camera

### ISSUE THREAD

**Issue by ohanamit** [seikan/homebridge-mi-camera#1]
when i run the discover command i find the camera according to the ip but there is no token. it appear Token: ???
how to find the token for the Json file?

**Comment by w729** [comment]
can't find mi camera,why??

**Comment by seikan** [comment]
Hi, please update the `miio` module and try again.

**Comment by FamJohansson** [comment]
@seikan 
Hello,
I have installed your fantastic plugin.. But I have not yet manage to get listed the token..
I Have updated the miio module with no good result.. 

When i run the miio --discover --sync command it just lists up 
Device ID: 69219546

Model info: Unknown
Address: 192.168.1.41
Token: ???
Support: Unknown



Will this plugin support all camera from xiaomi?

**Comment by roboterm** [comment]
I got same results with the Xiaomi Chuangmi. 
Token: ???
Support: Unknown
