### ISSUE TITLE
Does this Work with Xiaomi Mi security Smart Webcam?

### ISSUE THREAD

**Issue by tomsteenbakkers** [seikan/homebridge-mi-camera#2]
Hi,

I have homebridge running with all the security products of Xiaomi. Now I want to add the cheap and simple camera Xiaomi Mi security camera. 

This is not the one you are using in the read me but this one. 
![image](https://user-images.githubusercontent.com/24613800/34457695-acc540bc-edb9-11e7-8b8f-0acd3643cde1.png)

Does your plugin support this camera?

**Comment by seikan** [comment]
Hi, I do not have this device to confirm its compability.
 I think it's working as it may using different protocol.

**Comment by roboterm** [comment]
It doesn’t work with that Xiaomi Chuangmi. I bought that cam and miio couldn’t find out the IP.
